name: main

on:
  schedule:
    - cron: "0 3 * * *" # 00:00 horário de Brasília (UTC-3)
  workflow_dispatch: # permite rodar manualmente pelo GitHub também

jobs:
  criar-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Instalar dependências
        run: bun install

      - name: Compilar TypeScript
        run: bun run build

      - name: Rodar script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: node dist/index.js
